Bump lower bound on mtl
The use of `liftEither` in `Refined.Internal` requires `mtl >= 2.2.2`:

```
[2 of 8] Compiling Refined.Internal ( src/Refined/Internal.hs, dist/build/Refined/Internal.o )
src/Refined/Internal.hs:1112:16: error:
    Not in scope: ‘MonadError.liftEither’
    Module ‘Control.Monad.Error.Class’ does not export ‘liftEither’.
     |
1112 | exceptRefine = MonadError.liftEither
     |                ^^^^^^^^^^^^^^^^^^^^^
```